import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "./context/AuthContext";
import { PostProvider } from "./context/postContext";
import { ModalProvider } from "./context/modalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PostOneApp",
  description: "Generated by PostOneApp",
};

import Navbar from "./components/navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemesProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <PostProvider>
              <ModalProvider>
                <Navbar />
                {children}
              </ModalProvider>
            </PostProvider>
          </AuthProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
